import { assets } from '@/assets';

export const marketTable = [
  {
    icon: assets.ethIcon,
    name: 'USDT',
    collateral: '$513.854',
    tvl: '29.3M',
    mcr: '150%',
    apr: '9.50%',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: 'ETH',
    collateral: '$513.854',
    tvl: '29.3M',
    mcr: '150%',
    apr: '9.50%',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: 'BTC',
    collateral: '$513.854',
    tvl: '29.3M',
    mcr: '190%',
    apr: '9.50%',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: 'BASE',
    collateral: '$513.854',
    tvl: '29.3M',
    mcr: '150%',
    apr: '9.50%',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: 'BNB',
    collateral: '$513.854',
    tvl: '29.3M',
    mcr: '150%',
    apr: '9.50%',
    details: 'Details',
  },
];

export const supplyTable = [
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    supply: 'Supply',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    supply: 'Supply',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' BNB',
    balance: '$0.372bnb',
    apy: '7.8%',
    status: 'Inactive',
    supply: 'Supply',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    supply: 'Supply',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' USDT',
    balance: '1.963usdt',
    apy: '2.9%',
    status: 'Inactive',
    supply: 'Supply',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    supply: 'Supply',
    details: 'Details',
  },
];
export const borrowTable = [
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    borrow: 'Borrow',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    borrow: 'borrow',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' BNB',
    balance: '$0.372bnb',
    apy: '7.8%',
    status: 'Inactive',
    borrow: 'borrow',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    borrow: 'borrow',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' USDT',
    balance: '1.963usdt',
    apy: '2.9%',
    status: 'Inactive',
    borrow: 'borrow',
    details: 'Details',
  },
  {
    icon: assets.ethIcon,
    name: ' cbETH',
    balance: '0.653eth',
    apy: '0.4%',
    status: 'Live',
    borrow: 'borrow',
    details: 'Details',
  },
];

export const wallets = [
  {
    icon: assets.metamask,
    name: 'Browser Wallet',
  },

  {
    icon: assets.coinbase,
    name: 'Coinbase Wallet',
  },

  {
    icon: assets.phantom,
    name: 'WalletConnect',
  },
];
